-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 08:19:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ProjentoInter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjentoInter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjentoInter` ;
USE `ProjentoInter` ;

-- -----------------------------------------------------
-- Table `ProjentoInter`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`jogos` (
  `idjogos` INT NOT NULL AUTO_INCREMENT,
  `nomejogos` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idjogos`),
  INDEX `fk_jogos_usuario_idx` (`idusuario` ASC),
  CONSTRAINT `fk_jogos_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_categoria_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`noticia` (
  `idnoticia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  `idjogos` INT NOT NULL,
  PRIMARY KEY (`idnoticia`),
  INDEX `fk_noticia_usuario1_idx` (`idusuario` ASC) ,
  INDEX `fk_noticia_categoria1_idx` (`idcategoria` ASC) ,
  INDEX `fk_noticia_jogos1_idx` (`idjogos` ASC) ,
  CONSTRAINT `fk_noticia_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `ProjentoInter`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_jogos1`
    FOREIGN KEY (`idjogos`)
    REFERENCES `ProjentoInter`.`jogos` (`idjogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`favoritos` (
  `idusuario` INT NOT NULL,
  `idjogos` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idjogos`),
  INDEX `fk_usuario_has_jogos_jogos1_idx` (`idjogos` ASC) ,
  INDEX `fk_usuario_has_jogos_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_usuario_has_jogos_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_jogos_jogos1`
    FOREIGN KEY (`idjogos`)
    REFERENCES `ProjentoInter`.`jogos` (`idjogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`cometariojogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`cometariojogos` (
  `idcometariojogos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `idjogos` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcometariojogos`),
  INDEX `fk_cometariojogos_jogos1_idx` (`idjogos` ASC) ,
  INDEX `fk_cometariojogos_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_cometariojogos_jogos1`
    FOREIGN KEY (`idjogos`)
    REFERENCES `ProjentoInter`.`jogos` (`idjogos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cometariojogos_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`cometarionoticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`cometarionoticia` (
  `idcometarionoticia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `idnoticia` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idcometarionoticia`),
  INDEX `fk_cometarionoticia_noticia1_idx` (`idnoticia` ASC) ,
  INDEX `fk_cometarionoticia_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_cometarionoticia_noticia1`
    FOREIGN KEY (`idnoticia`)
    REFERENCES `ProjentoInter`.`noticia` (`idnoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cometarionoticia_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjentoInter`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjentoInter`.`evento` (
  `idevento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fk_evento_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_evento_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `ProjentoInter`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
